"""Add status, closing_date, actual_pl, closing_notes to Trade model

Revision ID: 566f869c7f61
Revises: 7dc5727bbd25
Create Date: 2025-06-28 16:37:26.384439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566f869c7f61'
down_revision = '7dc5727bbd25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('closing_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_pl', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('closing_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('closing_notes')
        batch_op.drop_column('actual_pl')
        batch_op.drop_column('closing_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
