"""Add tags to Trade model

Revision ID: e93a1fa958c0
Revises: 566f869c7f61
Create Date: 2025-06-30 03:47:42.115126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93a1fa958c0'
down_revision = '566f869c7f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
